
\c learnia_question_db;

-- Questions Table
-- Student questions
CREATE TABLE questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    document_id UUID,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    is_resolved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Answers Table
-- Answers to questions (AI-generated or manual)
CREATE TABLE answers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID NOT NULL,
    content TEXT NOT NULL,
    is_ai_generated BOOLEAN NOT NULL DEFAULT false,
    source_chunks JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Indexes for questions
CREATE INDEX idx_questions_user_id_created_at ON questions(user_id, created_at DESC);
CREATE INDEX idx_questions_workspace_id_created_at ON questions(workspace_id, created_at DESC);
CREATE INDEX idx_questions_document_id ON questions(document_id);
CREATE INDEX idx_questions_is_resolved ON questions(is_resolved);
CREATE INDEX idx_questions_created_at ON questions(created_at DESC);

-- Indexes for answers
CREATE INDEX idx_answers_question_id_created_at ON answers(question_id, created_at DESC);
CREATE INDEX idx_answers_is_ai_generated ON answers(is_ai_generated);

-- GIN index for JSONB source_chunks queries
CREATE INDEX idx_answers_source_chunks ON answers USING GIN (source_chunks);

-- Comments for documentation
COMMENT ON TABLE questions IS 'Student questions about course content or documents';
COMMENT ON TABLE answers IS 'Answers to questions, either AI-generated or manually created';
COMMENT ON COLUMN questions.user_id IS 'Reference to user ID in user service (UUID)';
COMMENT ON COLUMN questions.workspace_id IS 'Reference to workspace ID in course service (UUID)';
COMMENT ON COLUMN questions.document_id IS 'Reference to document ID in document service, NULL if question is about general course content';
COMMENT ON COLUMN answers.is_ai_generated IS 'True if answer was generated by AI, false if manually created';
COMMENT ON COLUMN answers.source_chunks IS 'JSON array of content chunk IDs used to generate the answer';
