spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/learnia_auth_db
    username: ${DB_USERNAME:learnia_user}
    password: ${DB_PASSWORD:learnia_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false

  flyway:
    enabled: false

server:
  port: 8081

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173}
